# Generated by Django 4.2.7 on 2023-11-28 10:21

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0002_profile_created"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="created",
        ),
    ]
