# Generated by Django 4.2.7 on 2023-11-28 10:21

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0003_remove_profile_created"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="created",
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
