# Generated by Django 4.2.7 on 2023-11-28 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0006_alter_album_options_and_more"),
        ("account", "0005_profile_album"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="album",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="album.album",
            ),
        ),
    ]
