# Generated by Django 4.2.7 on 2023-11-28 16:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0006_alter_profile_album"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="album",
        ),
    ]
