# Generated by Django 4.2.7 on 2023-11-28 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0006_alter_album_options_and_more"),
        ("account", "0007_remove_profile_album"),
    ]

    operations = [
        migrations.AddField(
            model_name="profile",
            name="albums",
            field=models.ManyToManyField(to="album.album"),
        ),
    ]
