# Generated by Django 4.2.7 on 2023-11-28 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0006_alter_album_options_and_more"),
        ("account", "0008_profile_albums"),
    ]

    operations = [
        migrations.AlterField(
            model_name="profile",
            name="albums",
            field=models.ManyToManyField(blank=True, to="album.album"),
        ),
    ]
