# Generated by Django 4.2.7 on 2023-11-28 16:56

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("account", "0009_alter_profile_albums"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="profile",
            name="albums",
        ),
    ]
