# Generated by Django 4.2.7 on 2023-11-30 18:40

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("actions", "0002_action_delete_actions_and_more"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Action",
            new_name="Actions",
        ),
        migrations.RenameIndex(
            model_name="actions",
            new_name="actions_act_created_639f69_idx",
            old_name="actions_act_created_64f10d_idx",
        ),
        migrations.RenameIndex(
            model_name="actions",
            new_name="actions_act_target__5ecc2e_idx",
            old_name="actions_act_target__f20513_idx",
        ),
    ]
