# Generated by Django 4.2.7 on 2023-11-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='album',
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='images_albu_created_aa951f_idx',
        ),
        migrations.AddField(
            model_name='album',
            name='slug',
            field=models.SlugField(default=0, max_length=200, unique=True),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Image',
        ),
    ]
