# Generated by Django 4.2.7 on 2023-11-20 08:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_image_album_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/')),
                ('album', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='images.album')),
            ],
        ),
    ]
