# Generated by Django 4.2.7 on 2023-11-20 09:03

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
