# Generated by Django 4.2.7 on 2023-11-20 09:08

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0005_alter_album_created'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['-publish']},
        ),
        migrations.RemoveField(
            model_name='album',
            name='created',
        ),
        migrations.AddField(
            model_name='album',
            name='publish',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
