# Generated by Django 4.2.7 on 2023-11-20 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0006_alter_album_options_remove_album_created_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('DF', 'Draft'), ('PB', 'Published')], default='DF', max_length=2),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['-publish'], name='images_albu_publish_293db6_idx'),
        ),
    ]
