# Generated by Django 4.2.7 on 2023-11-20 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0007_album_status_album_images_albu_publish_293db6_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
