# Generated by Django 4.2.7 on 2023-11-20 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0008_alter_image_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='add',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
