# Generated by Django 4.2.7 on 2023-11-20 12:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0009_image_add'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='add',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='image',
            name='album',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='images.album'),
        ),
    ]
