# Generated by Django 4.2.7 on 2023-11-21 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='album',
            name='users_like',
        ),
    ]
