# Generated by Django 4.2.7 on 2023-11-21 15:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('album', '0002_remove_album_slug_remove_album_users_like'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='update',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='album',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='album', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('PR', 'Private'), ('PB', 'Public')], default='PB', max_length=2),
        ),
    ]
