# Generated by Django 4.2.7 on 2023-11-24 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_remove_album_image_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='album',
            options={'ordering': ['title']},
        ),
        migrations.RemoveIndex(
            model_name='album',
            name='album_album_publish_ebd4d8_idx',
        ),
        migrations.AlterField(
            model_name='album',
            name='status',
            field=models.CharField(choices=[('PR', 'Private'), ('PB', 'Public')], default='PR', max_length=2),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AddIndex(
            model_name='album',
            index=models.Index(fields=['title'], name='album_album_title_014926_idx'),
        ),
    ]
