# Generated by Django 4.2.7 on 2023-11-21 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0003_album_update_alter_album_author_alter_album_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='title',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
