# Generated by Django 4.2.7 on 2023-11-26 09:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0005_alter_album_status_alter_image_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="album",
            options={"ordering": ["-update"]},
        ),
        migrations.RemoveIndex(
            model_name="album",
            name="album_album_title_014926_idx",
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["-update"], name="album_album_update_998799_idx"
            ),
        ),
    ]
