# Generated by Django 4.2.7 on 2023-11-29 08:59

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("album", "0006_alter_album_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="users_like",
            field=models.ManyToManyField(
                blank=True, related_name="albums_liked", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
