# Generated by Django 4.2.7 on 2023-11-21 17:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('album', '0006_album_cover_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='cover_image',
        ),
    ]
