# Generated by Django 4.2.7 on 2023-12-03 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0008_comment"),
    ]

    operations = [
        migrations.AddField(
            model_name="album",
            name="total_likes",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddIndex(
            model_name="album",
            index=models.Index(
                fields=["-total_likes"], name="album_album_total_l_1e1d4d_idx"
            ),
        ),
    ]
