# Generated by Django 4.2.7 on 2023-12-04 16:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0009_album_total_likes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="body",
            field=models.TextField(blank=True),
        ),
    ]
