# Generated by Django 4.2.7 on 2023-12-04 22:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0010_alter_comment_body"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.FileField(upload_to="images/"),
        ),
    ]
