# Generated by Django 4.2.7 on 2023-12-04 22:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("album", "0011_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(upload_to="images/"),
        ),
    ]
